### ISSUE TITLE
Probabilistic Payments

### ISSUE THREAD

**Issue by Gustav-Simonsson** [hoprnet/hopr-core#172]
Have HOPR considered using probabilistic micropayments?

The advantage over payment channels is that it avoids the need for one on-chain funding tx per recipient.

Instead, payments can be sent immediately to any number of (new) recipients - only a single on-chain tx is needed to lockup an amount of tokens, which can then be used to send off-chain payments to any number of recipients.

Payment ticket frequency and winning probability can be configured to support payment per individual packet or any larger amount of data as well as any number of on-chain settlement txs over time.

Livepeer has a good writeup on their recent development of probabilistic payments (all open source and free to use): https://medium.com/livepeer-blog/streamflow-probabilistic-micropayments-f3a647672462

**Comment by robertkiel** [comment]
Thanks for the great link :-)

Right now, we are using a combination of "vanilla" payment channels together with probabilistic micropayments for our proof-of-relay scheme.

This is how it is at the moment. So, since we are continuously improving our payment scheme, we intend to move closer towards probablistic micropayments.
